### ISSUE TITLE
sending EventGA using GampBundle

### ISSUE THREAD

**Issue by Venzon** [fourlabsldn/GampBundle#13]
Hi

Is it possible to send google analitics request for EventGa just to log website entry to statistics?
Code below does not work:
```
$this->get('gamp.analytics')
->setEventCategory('test')
->setEventAction('test')
->setEventLabel('test')
->sendEvent()
```
Best Regards

**Comment by Nightbr** [comment]
Please explain your problem (does not work is not enough). I used the same code and it works fine. You should debug a little before create and issue.

BTW: issue tracker is not support tracker

**Comment by Venzon** [comment]
Sorry for bothering
All works fine
