### ISSUE TITLE
Symfony4 support

### ISSUE THREAD

**Issue by MrNicodemuz** [fourlabsldn/GampBundle#17]
Is it possible to add Symfony4 support?

**Comment by foaly-nr1** [comment]
Sure. Are you able to work on a pull request @MrNicodemuz ?

**Comment by n3r0-ch** [comment]
Take a look at #18

**Comment by foaly-nr1** [comment]
Resolved in https://github.com/fourlabsldn/GampBundle/commit/42d741c2c70baab42bf65bbb7888d152a83a1758.
