### ISSUE TITLE
Generate two tags for php-ga-measurement-protocol ^2.0 and ^1.1

### ISSUE THREAD

**Issue by Nightbr** [fourlabsldn/GampBundle#2]
Hello,

I have a dependencies issue with GampBundle. In my project I already have dependencies which requires **guzzlehttp/guzzle 5.x**. 
But here we are, GampBundle (great bundle!) require `"theiconic/php-ga-measurement-protocol": "^2.0" `which require **guzzlehttp/guzzle 6**

It would be really nice if you could made two versions of GampBundle:

* One which require `"theiconic/php-ga-measurement-protocol": "^1.1"` for Guzzle 5
* and another which require `"theiconic/php-ga-measurement-protocol": "^2.0"` for Guzzle 6

[Doc here](https://github.com/theiconic/php-ga-measurement-protocol#installation)

I am really stuck and I prefer use the main repository of the project whereas using a fork. I think it can be usefull for everyone!

Thanks in advance.

Regards,

Titouan

**Comment by foaly-nr1** [comment]
Done https://packagist.org/packages/fourlabs/gamp-bundle. Thanks for your contribution!
