### ISSUE TITLE
createAnalytics method in factory throws InvalidArgumentException when no user-agent set

### ISSUE THREAD

**Issue by JunkMyFunk** [fourlabsldn/GampBundle#9]
Injecting this service into another service causes the `createAnalytics()` method to be called, which accesses the request stack to get the `User-Agent` header. In the case this is not set (which often happens with requests from bots or 3rd party API callbacks) an exception is thrown. Since this happens when the services are instantiated, it's hard to handle gracefully.

Passing an empty string to the `setUserAgentOverride()` method does not throw an exception, only a null value does. Since the user-agent isn't required by the GAMP API anyway, it seems this method should not be called in the constructor or gracefully handle a null value.

**Comment by foaly-nr1** [comment]
Thanks @JunkMyFunk. Are you happy to open a pull request?
